stages:
  - build
  - deploy

pages:
  tags:
    - pages-builder
  stage: deploy
  script:
    - dummy
  variables:
    BUILDER: 'mkdocs'
    WORKING_DIR: ''
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

rust_musl_build:
  stage: build
  tags:
    - rust
  only:
    - main
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/accipit
